// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

package com_asp_proto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type MessageType int32

const (
	MessageType_GET_SERVER_LIST_REQUEST              MessageType = 1
	MessageType_GET_SERVER_LIST_RESPONSE             MessageType = 2
	MessageType_GET_SUPPORTED_CITY_REQUEST           MessageType = 15
	MessageType_GET_SUPPORTED_CITY_RESPONSE          MessageType = 16
	MessageType_SAVE_GET_SETTING_REQUEST             MessageType = 23
	MessageType_SAVE_GET_SETTING_RESPONSE            MessageType = 24
	MessageType_SUBMIT_ADVISE_REQUEST                MessageType = 25
	MessageType_CHECK_UPDATES_REQUEST                MessageType = 34
	MessageType_CHECK_UPDATES_RESPONSE               MessageType = 35
	MessageType_GET_APPSTORE_URL_REQUEST             MessageType = 37
	MessageType_GET_APPSTORE_URL_RESPONSE            MessageType = 38
	MessageType_GET_SUPPORT_CAR_TYPE_REQUEST         MessageType = 41
	MessageType_GET_SUPPORT_CAR_TYPE_RESPONSE        MessageType = 42
	MessageType_SUBMIT_CAR_RENT_ORDER_REQUEST        MessageType = 53
	MessageType_SUBMIT_CAR_RENT_ORDER_RESPONSE       MessageType = 54
	MessageType_CANCEL_CAR_RENT_ORDER_REQUEST        MessageType = 62
	MessageType_CANCEL_CAR_RENT_ORDER_RESPONSE       MessageType = 63
	MessageType_QUERY_CAR_RENT_ORDER_STATUS_REQUEST  MessageType = 71
	MessageType_QUERY_CAR_RENT_ORDER_STATUS_RESPONSE MessageType = 72
	MessageType_APP_USER_REGIST                      MessageType = 100
	MessageType_APP_USER_LOGIN                       MessageType = 101
	MessageType_APP_USER_LOGOUT                      MessageType = 102
	MessageType_NOTIFY_MESSAGE                       MessageType = 999
	MessageType_ERROR_MESSAGE                        MessageType = 1000
	MessageType_UPDATE_CRYPT_KEY                     MessageType = 1001
)

var MessageType_name = map[int32]string{
	1:    "GET_SERVER_LIST_REQUEST",
	2:    "GET_SERVER_LIST_RESPONSE",
	15:   "GET_SUPPORTED_CITY_REQUEST",
	16:   "GET_SUPPORTED_CITY_RESPONSE",
	23:   "SAVE_GET_SETTING_REQUEST",
	24:   "SAVE_GET_SETTING_RESPONSE",
	25:   "SUBMIT_ADVISE_REQUEST",
	34:   "CHECK_UPDATES_REQUEST",
	35:   "CHECK_UPDATES_RESPONSE",
	37:   "GET_APPSTORE_URL_REQUEST",
	38:   "GET_APPSTORE_URL_RESPONSE",
	41:   "GET_SUPPORT_CAR_TYPE_REQUEST",
	42:   "GET_SUPPORT_CAR_TYPE_RESPONSE",
	53:   "SUBMIT_CAR_RENT_ORDER_REQUEST",
	54:   "SUBMIT_CAR_RENT_ORDER_RESPONSE",
	62:   "CANCEL_CAR_RENT_ORDER_REQUEST",
	63:   "CANCEL_CAR_RENT_ORDER_RESPONSE",
	71:   "QUERY_CAR_RENT_ORDER_STATUS_REQUEST",
	72:   "QUERY_CAR_RENT_ORDER_STATUS_RESPONSE",
	100:  "APP_USER_REGIST",
	101:  "APP_USER_LOGIN",
	102:  "APP_USER_LOGOUT",
	999:  "NOTIFY_MESSAGE",
	1000: "ERROR_MESSAGE",
	1001: "UPDATE_CRYPT_KEY",
}
var MessageType_value = map[string]int32{
	"GET_SERVER_LIST_REQUEST":              1,
	"GET_SERVER_LIST_RESPONSE":             2,
	"GET_SUPPORTED_CITY_REQUEST":           15,
	"GET_SUPPORTED_CITY_RESPONSE":          16,
	"SAVE_GET_SETTING_REQUEST":             23,
	"SAVE_GET_SETTING_RESPONSE":            24,
	"SUBMIT_ADVISE_REQUEST":                25,
	"CHECK_UPDATES_REQUEST":                34,
	"CHECK_UPDATES_RESPONSE":               35,
	"GET_APPSTORE_URL_REQUEST":             37,
	"GET_APPSTORE_URL_RESPONSE":            38,
	"GET_SUPPORT_CAR_TYPE_REQUEST":         41,
	"GET_SUPPORT_CAR_TYPE_RESPONSE":        42,
	"SUBMIT_CAR_RENT_ORDER_REQUEST":        53,
	"SUBMIT_CAR_RENT_ORDER_RESPONSE":       54,
	"CANCEL_CAR_RENT_ORDER_REQUEST":        62,
	"CANCEL_CAR_RENT_ORDER_RESPONSE":       63,
	"QUERY_CAR_RENT_ORDER_STATUS_REQUEST":  71,
	"QUERY_CAR_RENT_ORDER_STATUS_RESPONSE": 72,
	"APP_USER_REGIST":                      100,
	"APP_USER_LOGIN":                       101,
	"APP_USER_LOGOUT":                      102,
	"NOTIFY_MESSAGE":                       999,
	"ERROR_MESSAGE":                        1000,
	"UPDATE_CRYPT_KEY":                     1001,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x MessageType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}

type ErrorType int32

const (
	ErrorType_UNKNOWN_ERROR     ErrorType = 0
	ErrorType_ORDERID_DUPLICATE ErrorType = 1
	ErrorType_ORDERID_NOTFOULD  ErrorType = 2
)

var ErrorType_name = map[int32]string{
	0: "UNKNOWN_ERROR",
	1: "ORDERID_DUPLICATE",
	2: "ORDERID_NOTFOULD",
}
var ErrorType_value = map[string]int32{
	"UNKNOWN_ERROR":     0,
	"ORDERID_DUPLICATE": 1,
	"ORDERID_NOTFOULD":  2,
}

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}
func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}
func (x ErrorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorType_value, data, "ErrorType")
	if err != nil {
		return err
	}
	*x = ErrorType(value)
	return nil
}

type UpdatedCryptKey struct {
	NewKey           *string `protobuf:"bytes,1,req,name=new_key" json:"new_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdatedCryptKey) Reset()         { *m = UpdatedCryptKey{} }
func (m *UpdatedCryptKey) String() string { return proto.CompactTextString(m) }
func (*UpdatedCryptKey) ProtoMessage()    {}

func (m *UpdatedCryptKey) GetNewKey() string {
	if m != nil && m.NewKey != nil {
		return *m.NewKey
	}
	return ""
}

func init() {
	proto.RegisterEnum("com.asp.proto.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("com.asp.proto.ErrorType", ErrorType_name, ErrorType_value)
}
