// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

package com_asp_proto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ISPType int32

const (
	ISPType_CHINA_TELECOM ISPType = 1
	ISPType_CHINA_UNICOM  ISPType = 2
)

var ISPType_name = map[int32]string{
	1: "CHINA_TELECOM",
	2: "CHINA_UNICOM",
}
var ISPType_value = map[string]int32{
	"CHINA_TELECOM": 1,
	"CHINA_UNICOM":  2,
}

func (x ISPType) Enum() *ISPType {
	p := new(ISPType)
	*p = x
	return p
}
func (x ISPType) String() string {
	return proto.EnumName(ISPType_name, int32(x))
}
func (x ISPType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ISPType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ISPType_value, data, "ISPType")
	if err != nil {
		return err
	}
	*x = ISPType(value)
	return nil
}

type MobileDeviceType int32

const (
	MobileDeviceType_IPHONE  MobileDeviceType = 1
	MobileDeviceType_ANDROID MobileDeviceType = 2
	MobileDeviceType_WINDOWS MobileDeviceType = 3
)

var MobileDeviceType_name = map[int32]string{
	1: "IPHONE",
	2: "ANDROID",
	3: "WINDOWS",
}
var MobileDeviceType_value = map[string]int32{
	"IPHONE":  1,
	"ANDROID": 2,
	"WINDOWS": 3,
}

func (x MobileDeviceType) Enum() *MobileDeviceType {
	p := new(MobileDeviceType)
	*p = x
	return p
}
func (x MobileDeviceType) String() string {
	return proto.EnumName(MobileDeviceType_name, int32(x))
}
func (x MobileDeviceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *MobileDeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MobileDeviceType_value, data, "MobileDeviceType")
	if err != nil {
		return err
	}
	*x = MobileDeviceType(value)
	return nil
}

type AppstoreUrlType int32

const (
	AppstoreUrlType_INSTALL_URL AppstoreUrlType = 1
	AppstoreUrlType_REVIEW_URL  AppstoreUrlType = 2
)

var AppstoreUrlType_name = map[int32]string{
	1: "INSTALL_URL",
	2: "REVIEW_URL",
}
var AppstoreUrlType_value = map[string]int32{
	"INSTALL_URL": 1,
	"REVIEW_URL":  2,
}

func (x AppstoreUrlType) Enum() *AppstoreUrlType {
	p := new(AppstoreUrlType)
	*p = x
	return p
}
func (x AppstoreUrlType) String() string {
	return proto.EnumName(AppstoreUrlType_name, int32(x))
}
func (x AppstoreUrlType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *AppstoreUrlType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AppstoreUrlType_value, data, "AppstoreUrlType")
	if err != nil {
		return err
	}
	*x = AppstoreUrlType(value)
	return nil
}

type SupportCarRentalType int32

const (
	SupportCarRentalType_AIRPORT_ARRIVAL   SupportCarRentalType = 1
	SupportCarRentalType_AIRPORT_DEPARTURE SupportCarRentalType = 2
	SupportCarRentalType_HOURLY_RENTAL     SupportCarRentalType = 3
)

var SupportCarRentalType_name = map[int32]string{
	1: "AIRPORT_ARRIVAL",
	2: "AIRPORT_DEPARTURE",
	3: "HOURLY_RENTAL",
}
var SupportCarRentalType_value = map[string]int32{
	"AIRPORT_ARRIVAL":   1,
	"AIRPORT_DEPARTURE": 2,
	"HOURLY_RENTAL":     3,
}

func (x SupportCarRentalType) Enum() *SupportCarRentalType {
	p := new(SupportCarRentalType)
	*p = x
	return p
}
func (x SupportCarRentalType) String() string {
	return proto.EnumName(SupportCarRentalType_name, int32(x))
}
func (x SupportCarRentalType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *SupportCarRentalType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SupportCarRentalType_value, data, "SupportCarRentalType")
	if err != nil {
		return err
	}
	*x = SupportCarRentalType(value)
	return nil
}

type OrderStatus int32

const (
	OrderStatus_SUBMITED  OrderStatus = 1
	OrderStatus_CONFIRMED OrderStatus = 2
	OrderStatus_CANCELED  OrderStatus = 3
	OrderStatus_COMPLETED OrderStatus = 4
)

var OrderStatus_name = map[int32]string{
	1: "SUBMITED",
	2: "CONFIRMED",
	3: "CANCELED",
	4: "COMPLETED",
}
var OrderStatus_value = map[string]int32{
	"SUBMITED":  1,
	"CONFIRMED": 2,
	"CANCELED":  3,
	"COMPLETED": 4,
}

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}
func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}
func (x OrderStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *OrderStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OrderStatus_value, data, "OrderStatus")
	if err != nil {
		return err
	}
	*x = OrderStatus(value)
	return nil
}

type ErrorMessage struct {
	ErrCode          *ErrorType `protobuf:"varint,1,req,name=err_code,enum=com.asp.proto.ErrorType" json:"err_code,omitempty"`
	ErrCause         *string    `protobuf:"bytes,2,req,name=err_cause" json:"err_cause,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ErrorMessage) Reset()         { *m = ErrorMessage{} }
func (m *ErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ErrorMessage) ProtoMessage()    {}

func (m *ErrorMessage) GetErrCode() ErrorType {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *ErrorMessage) GetErrCause() string {
	if m != nil && m.ErrCause != nil {
		return *m.ErrCause
	}
	return ""
}

type NotifyMessage struct {
	Success          *bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NotifyMessage) Reset()         { *m = NotifyMessage{} }
func (m *NotifyMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyMessage) ProtoMessage()    {}

func (m *NotifyMessage) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *NotifyMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type CityInfo struct {
	CityId           *int32  `protobuf:"varint,1,req,name=cityId" json:"cityId,omitempty"`
	CityName         *string `protobuf:"bytes,2,req,name=cityName" json:"cityName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CityInfo) Reset()         { *m = CityInfo{} }
func (m *CityInfo) String() string { return proto.CompactTextString(m) }
func (*CityInfo) ProtoMessage()    {}

func (m *CityInfo) GetCityId() int32 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

func (m *CityInfo) GetCityName() string {
	if m != nil && m.CityName != nil {
		return *m.CityName
	}
	return ""
}

type ServerItem struct {
	Host             *string `protobuf:"bytes,1,req,name=host" json:"host,omitempty"`
	Port             *int32  `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	IspType          *int32  `protobuf:"varint,3,req,name=isp_type" json:"isp_type,omitempty"`
	IspDesc          *string `protobuf:"bytes,4,req,name=isp_desc" json:"isp_desc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerItem) Reset()         { *m = ServerItem{} }
func (m *ServerItem) String() string { return proto.CompactTextString(m) }
func (*ServerItem) ProtoMessage()    {}

func (m *ServerItem) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *ServerItem) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *ServerItem) GetIspType() int32 {
	if m != nil && m.IspType != nil {
		return *m.IspType
	}
	return 0
}

func (m *ServerItem) GetIspDesc() string {
	if m != nil && m.IspDesc != nil {
		return *m.IspDesc
	}
	return ""
}

type GetServerListRequest struct {
	Uid              *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetServerListRequest) Reset()         { *m = GetServerListRequest{} }
func (m *GetServerListRequest) String() string { return proto.CompactTextString(m) }
func (*GetServerListRequest) ProtoMessage()    {}

func (m *GetServerListRequest) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

type GetServerListResponse struct {
	Items            []*ServerItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GetServerListResponse) Reset()         { *m = GetServerListResponse{} }
func (m *GetServerListResponse) String() string { return proto.CompactTextString(m) }
func (*GetServerListResponse) ProtoMessage()    {}

func (m *GetServerListResponse) GetItems() []*ServerItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetSupportedCityRequest struct {
	Uid              *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetSupportedCityRequest) Reset()         { *m = GetSupportedCityRequest{} }
func (m *GetSupportedCityRequest) String() string { return proto.CompactTextString(m) }
func (*GetSupportedCityRequest) ProtoMessage()    {}

func (m *GetSupportedCityRequest) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

type GetSupportedCityResponse struct {
	Cities           []*CityInfo `protobuf:"bytes,1,rep,name=cities" json:"cities,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GetSupportedCityResponse) Reset()         { *m = GetSupportedCityResponse{} }
func (m *GetSupportedCityResponse) String() string { return proto.CompactTextString(m) }
func (*GetSupportedCityResponse) ProtoMessage()    {}

func (m *GetSupportedCityResponse) GetCities() []*CityInfo {
	if m != nil {
		return m.Cities
	}
	return nil
}

type UserSetting struct {
	PushEnable       *bool  `protobuf:"varint,1,opt,name=push_enable" json:"push_enable,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UserSetting) Reset()         { *m = UserSetting{} }
func (m *UserSetting) String() string { return proto.CompactTextString(m) }
func (*UserSetting) ProtoMessage()    {}

func (m *UserSetting) GetPushEnable() bool {
	if m != nil && m.PushEnable != nil {
		return *m.PushEnable
	}
	return false
}

type SaveGetSettingRequest struct {
	City             *int32       `protobuf:"varint,1,req,name=city" json:"city,omitempty"`
	Uid              *string      `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	SaveSetting      *bool        `protobuf:"varint,3,req,name=save_setting" json:"save_setting,omitempty"`
	Setting          *UserSetting `protobuf:"bytes,4,opt,name=setting" json:"setting,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SaveGetSettingRequest) Reset()         { *m = SaveGetSettingRequest{} }
func (m *SaveGetSettingRequest) String() string { return proto.CompactTextString(m) }
func (*SaveGetSettingRequest) ProtoMessage()    {}

func (m *SaveGetSettingRequest) GetCity() int32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

func (m *SaveGetSettingRequest) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *SaveGetSettingRequest) GetSaveSetting() bool {
	if m != nil && m.SaveSetting != nil {
		return *m.SaveSetting
	}
	return false
}

func (m *SaveGetSettingRequest) GetSetting() *UserSetting {
	if m != nil {
		return m.Setting
	}
	return nil
}

type SaveGetSettingResponse struct {
	Setting          *UserSetting `protobuf:"bytes,1,opt,name=setting" json:"setting,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SaveGetSettingResponse) Reset()         { *m = SaveGetSettingResponse{} }
func (m *SaveGetSettingResponse) String() string { return proto.CompactTextString(m) }
func (*SaveGetSettingResponse) ProtoMessage()    {}

func (m *SaveGetSettingResponse) GetSetting() *UserSetting {
	if m != nil {
		return m.Setting
	}
	return nil
}

type SubmitAdviseRequest struct {
	City             *int32  `protobuf:"varint,1,req,name=city" json:"city,omitempty"`
	Uid              *string `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	Advise           *string `protobuf:"bytes,3,req,name=advise" json:"advise,omitempty"`
	Email            *string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SubmitAdviseRequest) Reset()         { *m = SubmitAdviseRequest{} }
func (m *SubmitAdviseRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitAdviseRequest) ProtoMessage()    {}

func (m *SubmitAdviseRequest) GetCity() int32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

func (m *SubmitAdviseRequest) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *SubmitAdviseRequest) GetAdvise() string {
	if m != nil && m.Advise != nil {
		return *m.Advise
	}
	return ""
}

func (m *SubmitAdviseRequest) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

type AppUserRegister struct {
	City             *int32            `protobuf:"varint,1,req,name=city" json:"city,omitempty"`
	Uid              *string           `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	DeviceType       *MobileDeviceType `protobuf:"varint,3,req,name=device_type,enum=com.asp.proto.MobileDeviceType" json:"device_type,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *AppUserRegister) Reset()         { *m = AppUserRegister{} }
func (m *AppUserRegister) String() string { return proto.CompactTextString(m) }
func (*AppUserRegister) ProtoMessage()    {}

func (m *AppUserRegister) GetCity() int32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

func (m *AppUserRegister) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *AppUserRegister) GetDeviceType() MobileDeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return 0
}

type AppUserLogin struct {
	City             *int32  `protobuf:"varint,1,req,name=city" json:"city,omitempty"`
	Uid              *string `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	AppVer           *string `protobuf:"bytes,3,opt,name=app_ver" json:"app_ver,omitempty"`
	AppOs            *string `protobuf:"bytes,4,opt,name=app_os" json:"app_os,omitempty"`
	PushToken        *string `protobuf:"bytes,5,opt,name=push_token" json:"push_token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppUserLogin) Reset()         { *m = AppUserLogin{} }
func (m *AppUserLogin) String() string { return proto.CompactTextString(m) }
func (*AppUserLogin) ProtoMessage()    {}

func (m *AppUserLogin) GetCity() int32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

func (m *AppUserLogin) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *AppUserLogin) GetAppVer() string {
	if m != nil && m.AppVer != nil {
		return *m.AppVer
	}
	return ""
}

func (m *AppUserLogin) GetAppOs() string {
	if m != nil && m.AppOs != nil {
		return *m.AppOs
	}
	return ""
}

func (m *AppUserLogin) GetPushToken() string {
	if m != nil && m.PushToken != nil {
		return *m.PushToken
	}
	return ""
}

type AppUserLogout struct {
	City             *int32  `protobuf:"varint,1,req,name=city" json:"city,omitempty"`
	Uid              *string `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppUserLogout) Reset()         { *m = AppUserLogout{} }
func (m *AppUserLogout) String() string { return proto.CompactTextString(m) }
func (*AppUserLogout) ProtoMessage()    {}

func (m *AppUserLogout) GetCity() int32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

func (m *AppUserLogout) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

type CheckUpdatesRequest struct {
	City             *int32            `protobuf:"varint,1,req,name=city" json:"city,omitempty"`
	Uid              *string           `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	DeviceType       *MobileDeviceType `protobuf:"varint,3,req,name=device_type,enum=com.asp.proto.MobileDeviceType" json:"device_type,omitempty"`
	Version          *string           `protobuf:"bytes,4,req,name=version" json:"version,omitempty"`
	InstallChannel   *string           `protobuf:"bytes,5,opt,name=install_channel" json:"install_channel,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *CheckUpdatesRequest) Reset()         { *m = CheckUpdatesRequest{} }
func (m *CheckUpdatesRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUpdatesRequest) ProtoMessage()    {}

func (m *CheckUpdatesRequest) GetCity() int32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

func (m *CheckUpdatesRequest) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *CheckUpdatesRequest) GetDeviceType() MobileDeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return 0
}

func (m *CheckUpdatesRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *CheckUpdatesRequest) GetInstallChannel() string {
	if m != nil && m.InstallChannel != nil {
		return *m.InstallChannel
	}
	return ""
}

type CheckUpdatesResponse struct {
	NewVersion       *string `protobuf:"bytes,1,opt,name=new_version" json:"new_version,omitempty"`
	AppstoreUrl      *string `protobuf:"bytes,2,opt,name=appstore_url" json:"appstore_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CheckUpdatesResponse) Reset()         { *m = CheckUpdatesResponse{} }
func (m *CheckUpdatesResponse) String() string { return proto.CompactTextString(m) }
func (*CheckUpdatesResponse) ProtoMessage()    {}

func (m *CheckUpdatesResponse) GetNewVersion() string {
	if m != nil && m.NewVersion != nil {
		return *m.NewVersion
	}
	return ""
}

func (m *CheckUpdatesResponse) GetAppstoreUrl() string {
	if m != nil && m.AppstoreUrl != nil {
		return *m.AppstoreUrl
	}
	return ""
}

type GetAppstoreURLRequest struct {
	City             *int32            `protobuf:"varint,1,req,name=city" json:"city,omitempty"`
	Uid              *string           `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	DeviceType       *MobileDeviceType `protobuf:"varint,3,req,name=device_type,enum=com.asp.proto.MobileDeviceType" json:"device_type,omitempty"`
	UrlType          *AppstoreUrlType  `protobuf:"varint,4,req,name=url_type,enum=com.asp.proto.AppstoreUrlType" json:"url_type,omitempty"`
	InstallChannel   *string           `protobuf:"bytes,5,opt,name=install_channel" json:"install_channel,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetAppstoreURLRequest) Reset()         { *m = GetAppstoreURLRequest{} }
func (m *GetAppstoreURLRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppstoreURLRequest) ProtoMessage()    {}

func (m *GetAppstoreURLRequest) GetCity() int32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

func (m *GetAppstoreURLRequest) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *GetAppstoreURLRequest) GetDeviceType() MobileDeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return 0
}

func (m *GetAppstoreURLRequest) GetUrlType() AppstoreUrlType {
	if m != nil && m.UrlType != nil {
		return *m.UrlType
	}
	return 0
}

func (m *GetAppstoreURLRequest) GetInstallChannel() string {
	if m != nil && m.InstallChannel != nil {
		return *m.InstallChannel
	}
	return ""
}

type GetAppstoreURLResponse struct {
	UrlType          *AppstoreUrlType `protobuf:"varint,1,req,name=url_type,enum=com.asp.proto.AppstoreUrlType" json:"url_type,omitempty"`
	Url              *string          `protobuf:"bytes,2,req,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GetAppstoreURLResponse) Reset()         { *m = GetAppstoreURLResponse{} }
func (m *GetAppstoreURLResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppstoreURLResponse) ProtoMessage()    {}

func (m *GetAppstoreURLResponse) GetUrlType() AppstoreUrlType {
	if m != nil && m.UrlType != nil {
		return *m.UrlType
	}
	return 0
}

func (m *GetAppstoreURLResponse) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

type GetSupportCarTypeRequest struct {
	City             *int32  `protobuf:"varint,1,req,name=city" json:"city,omitempty"`
	Uid              *string `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	Offset           *int32  `protobuf:"varint,3,req,name=offset" json:"offset,omitempty"`
	Count            *int32  `protobuf:"varint,4,req,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetSupportCarTypeRequest) Reset()         { *m = GetSupportCarTypeRequest{} }
func (m *GetSupportCarTypeRequest) String() string { return proto.CompactTextString(m) }
func (*GetSupportCarTypeRequest) ProtoMessage()    {}

func (m *GetSupportCarTypeRequest) GetCity() int32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

func (m *GetSupportCarTypeRequest) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *GetSupportCarTypeRequest) GetOffset() int32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *GetSupportCarTypeRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type CarTypeItem struct {
	CarTypeName      *string `protobuf:"bytes,1,req,name=carTypeName" json:"carTypeName,omitempty"`
	CarTypeId        *string `protobuf:"bytes,2,req,name=carTypeId" json:"carTypeId,omitempty"`
	Description      *string `protobuf:"bytes,3,req,name=description" json:"description,omitempty"`
	IconUrl          *string `protobuf:"bytes,4,req,name=iconUrl" json:"iconUrl,omitempty"`
	BaseFee          *int32  `protobuf:"varint,5,req,name=baseFee" json:"baseFee,omitempty"`
	ExtraFeePerHour  *int32  `protobuf:"varint,6,req,name=extraFeePerHour" json:"extraFeePerHour,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CarTypeItem) Reset()         { *m = CarTypeItem{} }
func (m *CarTypeItem) String() string { return proto.CompactTextString(m) }
func (*CarTypeItem) ProtoMessage()    {}

func (m *CarTypeItem) GetCarTypeName() string {
	if m != nil && m.CarTypeName != nil {
		return *m.CarTypeName
	}
	return ""
}

func (m *CarTypeItem) GetCarTypeId() string {
	if m != nil && m.CarTypeId != nil {
		return *m.CarTypeId
	}
	return ""
}

func (m *CarTypeItem) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *CarTypeItem) GetIconUrl() string {
	if m != nil && m.IconUrl != nil {
		return *m.IconUrl
	}
	return ""
}

func (m *CarTypeItem) GetBaseFee() int32 {
	if m != nil && m.BaseFee != nil {
		return *m.BaseFee
	}
	return 0
}

func (m *CarTypeItem) GetExtraFeePerHour() int32 {
	if m != nil && m.ExtraFeePerHour != nil {
		return *m.ExtraFeePerHour
	}
	return 0
}

type GetSupportCarTypeResponse struct {
	Items            []*CarTypeItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Rest             *int32         `protobuf:"varint,2,req,name=rest" json:"rest,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetSupportCarTypeResponse) Reset()         { *m = GetSupportCarTypeResponse{} }
func (m *GetSupportCarTypeResponse) String() string { return proto.CompactTextString(m) }
func (*GetSupportCarTypeResponse) ProtoMessage()    {}

func (m *GetSupportCarTypeResponse) GetItems() []*CarTypeItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *GetSupportCarTypeResponse) GetRest() int32 {
	if m != nil && m.Rest != nil {
		return *m.Rest
	}
	return 0
}

type CarRentOrderItem struct {
	OrderId           *string      `protobuf:"bytes,1,req,name=orderId" json:"orderId,omitempty"`
	RentTypeId        *int32       `protobuf:"varint,2,req,name=rentTypeId" json:"rentTypeId,omitempty"`
	CarTypeId         *string      `protobuf:"bytes,3,req,name=carTypeId" json:"carTypeId,omitempty"`
	StartDate         *string      `protobuf:"bytes,4,req,name=startDate" json:"startDate,omitempty"`
	ContactName       *string      `protobuf:"bytes,5,req,name=contactName" json:"contactName,omitempty"`
	ContactPhone      *string      `protobuf:"bytes,6,req,name=contactPhone" json:"contactPhone,omitempty"`
	ContactEmail      *string      `protobuf:"bytes,7,req,name=contactEmail" json:"contactEmail,omitempty"`
	PickUpAt          *string      `protobuf:"bytes,8,req,name=pickUpAt" json:"pickUpAt,omitempty"`
	Destination       *string      `protobuf:"bytes,9,req,name=destination" json:"destination,omitempty"`
	OrderStatus       *OrderStatus `protobuf:"varint,10,req,name=orderStatus,enum=com.asp.proto.OrderStatus" json:"orderStatus,omitempty"`
	FlightNumber      *string      `protobuf:"bytes,11,opt,name=flightNumber" json:"flightNumber,omitempty"`
	PlanRentHours     *string      `protobuf:"bytes,12,opt,name=planRentHours" json:"planRentHours,omitempty"`
	InvoiceTitle      *string      `protobuf:"bytes,13,opt,name=invoiceTitle" json:"invoiceTitle,omitempty"`
	NeedEnglishDriver *bool        `protobuf:"varint,14,opt,name=need_english_driver" json:"need_english_driver,omitempty"`
	XXX_unrecognized  []byte       `json:"-"`
}

func (m *CarRentOrderItem) Reset()         { *m = CarRentOrderItem{} }
func (m *CarRentOrderItem) String() string { return proto.CompactTextString(m) }
func (*CarRentOrderItem) ProtoMessage()    {}

func (m *CarRentOrderItem) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

func (m *CarRentOrderItem) GetRentTypeId() int32 {
	if m != nil && m.RentTypeId != nil {
		return *m.RentTypeId
	}
	return 0
}

func (m *CarRentOrderItem) GetCarTypeId() string {
	if m != nil && m.CarTypeId != nil {
		return *m.CarTypeId
	}
	return ""
}

func (m *CarRentOrderItem) GetStartDate() string {
	if m != nil && m.StartDate != nil {
		return *m.StartDate
	}
	return ""
}

func (m *CarRentOrderItem) GetContactName() string {
	if m != nil && m.ContactName != nil {
		return *m.ContactName
	}
	return ""
}

func (m *CarRentOrderItem) GetContactPhone() string {
	if m != nil && m.ContactPhone != nil {
		return *m.ContactPhone
	}
	return ""
}

func (m *CarRentOrderItem) GetContactEmail() string {
	if m != nil && m.ContactEmail != nil {
		return *m.ContactEmail
	}
	return ""
}

func (m *CarRentOrderItem) GetPickUpAt() string {
	if m != nil && m.PickUpAt != nil {
		return *m.PickUpAt
	}
	return ""
}

func (m *CarRentOrderItem) GetDestination() string {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return ""
}

func (m *CarRentOrderItem) GetOrderStatus() OrderStatus {
	if m != nil && m.OrderStatus != nil {
		return *m.OrderStatus
	}
	return 0
}

func (m *CarRentOrderItem) GetFlightNumber() string {
	if m != nil && m.FlightNumber != nil {
		return *m.FlightNumber
	}
	return ""
}

func (m *CarRentOrderItem) GetPlanRentHours() string {
	if m != nil && m.PlanRentHours != nil {
		return *m.PlanRentHours
	}
	return ""
}

func (m *CarRentOrderItem) GetInvoiceTitle() string {
	if m != nil && m.InvoiceTitle != nil {
		return *m.InvoiceTitle
	}
	return ""
}

func (m *CarRentOrderItem) GetNeedEnglishDriver() bool {
	if m != nil && m.NeedEnglishDriver != nil {
		return *m.NeedEnglishDriver
	}
	return false
}

type SubmitCarRentOrderRequest struct {
	City             *int32            `protobuf:"varint,1,req,name=city" json:"city,omitempty"`
	Uid              *string           `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	Order            *CarRentOrderItem `protobuf:"bytes,3,req,name=order" json:"order,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *SubmitCarRentOrderRequest) Reset()         { *m = SubmitCarRentOrderRequest{} }
func (m *SubmitCarRentOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitCarRentOrderRequest) ProtoMessage()    {}

func (m *SubmitCarRentOrderRequest) GetCity() int32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

func (m *SubmitCarRentOrderRequest) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *SubmitCarRentOrderRequest) GetOrder() *CarRentOrderItem {
	if m != nil {
		return m.Order
	}
	return nil
}

type SubmitCarRentOrderResponse struct {
	OrderId          *string      `protobuf:"bytes,1,req,name=orderId" json:"orderId,omitempty"`
	OrderStatus      *OrderStatus `protobuf:"varint,2,req,name=orderStatus,enum=com.asp.proto.OrderStatus" json:"orderStatus,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SubmitCarRentOrderResponse) Reset()         { *m = SubmitCarRentOrderResponse{} }
func (m *SubmitCarRentOrderResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitCarRentOrderResponse) ProtoMessage()    {}

func (m *SubmitCarRentOrderResponse) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

func (m *SubmitCarRentOrderResponse) GetOrderStatus() OrderStatus {
	if m != nil && m.OrderStatus != nil {
		return *m.OrderStatus
	}
	return 0
}

type CancelCarRentOrderRequest struct {
	City             *int32  `protobuf:"varint,1,req,name=city" json:"city,omitempty"`
	Uid              *string `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	OrderId          *string `protobuf:"bytes,3,req,name=orderId" json:"orderId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CancelCarRentOrderRequest) Reset()         { *m = CancelCarRentOrderRequest{} }
func (m *CancelCarRentOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CancelCarRentOrderRequest) ProtoMessage()    {}

func (m *CancelCarRentOrderRequest) GetCity() int32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

func (m *CancelCarRentOrderRequest) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *CancelCarRentOrderRequest) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

type CancelCarRentOrderResponse struct {
	OrderId          *string      `protobuf:"bytes,1,req,name=orderId" json:"orderId,omitempty"`
	OrderStatus      *OrderStatus `protobuf:"varint,2,req,name=orderStatus,enum=com.asp.proto.OrderStatus" json:"orderStatus,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CancelCarRentOrderResponse) Reset()         { *m = CancelCarRentOrderResponse{} }
func (m *CancelCarRentOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CancelCarRentOrderResponse) ProtoMessage()    {}

func (m *CancelCarRentOrderResponse) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

func (m *CancelCarRentOrderResponse) GetOrderStatus() OrderStatus {
	if m != nil && m.OrderStatus != nil {
		return *m.OrderStatus
	}
	return 0
}

type QueryCarRentOrderStatusRequest struct {
	City             *int32  `protobuf:"varint,1,req,name=city" json:"city,omitempty"`
	Uid              *string `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	OrderId          *string `protobuf:"bytes,3,req,name=orderId" json:"orderId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *QueryCarRentOrderStatusRequest) Reset()         { *m = QueryCarRentOrderStatusRequest{} }
func (m *QueryCarRentOrderStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCarRentOrderStatusRequest) ProtoMessage()    {}

func (m *QueryCarRentOrderStatusRequest) GetCity() int32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

func (m *QueryCarRentOrderStatusRequest) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *QueryCarRentOrderStatusRequest) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

type QueryCarRentOrderStatusResponse struct {
	OrderId          *string      `protobuf:"bytes,1,req,name=orderId" json:"orderId,omitempty"`
	OrderStatus      *OrderStatus `protobuf:"varint,2,req,name=orderStatus,enum=com.asp.proto.OrderStatus" json:"orderStatus,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *QueryCarRentOrderStatusResponse) Reset()         { *m = QueryCarRentOrderStatusResponse{} }
func (m *QueryCarRentOrderStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCarRentOrderStatusResponse) ProtoMessage()    {}

func (m *QueryCarRentOrderStatusResponse) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

func (m *QueryCarRentOrderStatusResponse) GetOrderStatus() OrderStatus {
	if m != nil && m.OrderStatus != nil {
		return *m.OrderStatus
	}
	return 0
}

func init() {
	proto.RegisterEnum("com.asp.proto.ISPType", ISPType_name, ISPType_value)
	proto.RegisterEnum("com.asp.proto.MobileDeviceType", MobileDeviceType_name, MobileDeviceType_value)
	proto.RegisterEnum("com.asp.proto.AppstoreUrlType", AppstoreUrlType_name, AppstoreUrlType_value)
	proto.RegisterEnum("com.asp.proto.SupportCarRentalType", SupportCarRentalType_name, SupportCarRentalType_value)
	proto.RegisterEnum("com.asp.proto.OrderStatus", OrderStatus_name, OrderStatus_value)
}
